# local_backend: true
backend:
  name: git-gateway
  # name: test-repo
  branch: master
media_folder: public/uploaded-img
public_folder: /uploaded-img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      editor:
        preview: false
      fields:
        - label: 'Portfolio'
          name: "portfolio"
          widget: list
          fields:
            - { label: "Project", name: "title", widget: "string"}
            - {label: "Grow", name: "grow", widget: "boolean", default: false}
            - { label: "Type", name: "type", widget: "select", options: ["Lighting Design", "Lighting Programmer", "Software", "Mechatronics", "Other Design"]}
            - { label: "Role", name: "role", widget: "string"}
            - { label: "Date", name: "date", widget: "number", min: 2000, max: 2100, step: 1}
            - { label: "Location", name: "location", widget: "string"}
            - label: "Crew"
              name: "crew"
              widget: "list"
              fields: 
              - { label: "Name", name: "name", widget: "string"}
              - { label: "Role", name: "role", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - label: "Photo"
              name: "photo"
              widget: "list"
              fields:
              - label: "Image" 
                name: "image"
                widget: "image"
                allow_multiple: false
              - label: "Caption"
                name: "caption"
                widget: "string"
                required: false
    - label: "Blog"
      name: "posts"
      file: "content/featured.md"
      editor:
        preview: false
      fields:
        - label: "Featured Posts"
          name: "post"
          widget: "relation"
          multiple: true
          min: 1
          max: 2
          collection: "blog"
          search_fields: ["title"]
          value_field: "{{slug}}"
          display_fields: ["title", "date"]
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {label: "Thumbnail", name: "thumbnail", widget: "image", allow_multiple: false}
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Hidden", name: "hidden", widget: "boolean", default: false }